### PR TITLE
Fix weird behavior of MaxPointCountDataPointsFilter

### LINKED ISSUE #463: Getting weird results/behavior from MaxPointCountDataPointsFilter
As the title suggest, I'm getting weird results from `MaxPointCountDataPointsFilter` as the point clouds don't seem to really have the number of point specified by the `maxCount` parameter.

Here's a videos to illustrate what I'm talking about:

[Current results video](https://youtu.be/yw0PLw_2KJE)

I will open a PR to show the results I get with the fix I made.

### PR DESCRIPTION
**Pull request by aguenette**
fixes #463

Like mentioned in the issues #463, this is the fix that I'm proposing in order to get better and more consistent results with the filter.

Here's a video showing the results:

[Fixed results video](https://youtu.be/m9oe-D1ZHY4)

### CODE REVIEW

File: pointmatcher/DataPointsFilters/MaxPointCount.cpp [hunk 1]
```diff
@@ -66,35 +67,20 @@ MaxPointCountDataPointsFilter<T>::filter(const DataPoints& input)
 template<typename T>
 void MaxPointCountDataPointsFilter<T>::inPlaceFilter(DataPoints& cloud)
 {
-	const size_t N = static_cast<size_t> (cloud.features.cols() - 1);
-	
-	if (maxCount <= N) 
+	const auto N = static_cast<size_t>(cloud.features.cols() - 1);
```
Comment (YoshuaNava) [inline pointmatcher/DataPointsFilters/MaxPointCount.cpp:70]:
```suggestion
	const size_t N{static_cast<size_t>(cloud.features.cols() - 1)};
```

If you use a known type with bracket initialization you can benefit from the compiler informing you in case there are narrowing casts 
https://stackoverflow.com/questions/42975620/in-c-can-we-use-for-c-style-casting

File: pointmatcher/DataPointsFilters/MaxPointCount.cpp [hunk 2]
```diff
@@ -66,35 +67,20 @@ MaxPointCountDataPointsFilter<T>::filter(const DataPoints& input)
...
+
+	if (maxCount <= N)
 	{
-		//Re-init seed at each call, to ensure same results
-		std::srand(seed);
-		
-		for(size_t j=0; j<maxCount; ++j)
+		std::default_random_engine randomNumberGenerator(seed);
+
+		for(size_t j = 0; j < maxCount; ++j)
```
Comment (YoshuaNava) [inline pointmatcher/DataPointsFilters/MaxPointCount.cpp:76]:
```suggestion
		for(size_t j{0u}; j < maxCount; ++j)
```

File: pointmatcher/DataPointsFilters/MaxPointCount.cpp [hunk 3]
```diff
@@ -66,35 +67,20 @@ MaxPointCountDataPointsFilter<T>::filter(const DataPoints& input)
...
-				cloud.descriptors.col(j) = cloud.descriptors.col(idx);
-				cloud.descriptors.col(idx) = desc;
-			}
-			if (cloud.times.cols() > 0)
-			{
-				const auto time = cloud.times.col(j);
-				cloud.times.col(j) = cloud.times.col(idx);
-				cloud.times.col(idx) = time;
-			}	
+			std::uniform_int_distribution<size_t> distribution(j, N);
```
Comment (YoshuaNava) [inline pointmatcher/DataPointsFilters/MaxPointCount.cpp:79]: How expensive is this operation?

File: pointmatcher/DataPointsFilters/MaxPointCount.cpp [hunk 4]
```diff
@@ -66,35 +67,20 @@ MaxPointCountDataPointsFilter<T>::filter(const DataPoints& input)
...
-	if (maxCount <= N) 
+	const auto N = static_cast<size_t>(cloud.features.cols() - 1);
+
+	if (maxCount <= N)
 	{
-		//Re-init seed at each call, to ensure same results
-		std::srand(seed);
-		
-		for(size_t j=0; j<maxCount; ++j)
+		std::default_random_engine randomNumberGenerator(seed);
```
Comment (YoshuaNava) [inline pointmatcher/DataPointsFilters/MaxPointCount.cpp:74]: What is the default random engine? Did you evaluate it against other options?

File: pointmatcher/DataPointsFilters/MaxPointCount.cpp [hunk 5]
```diff
@@ -66,35 +67,20 @@ MaxPointCountDataPointsFilter<T>::filter(const DataPoints& input)
...
-			{
-				const auto time = cloud.times.col(j);
-				cloud.times.col(j) = cloud.times.col(idx);
-				cloud.times.col(idx) = time;
-			}	
+			std::uniform_int_distribution<size_t> distribution(j, N);
+			const size_t index = distribution(randomNumberGenerator);
+
+			//Switch columns j and index
+			cloud.swapCols(j, index);
```
Comment (YoshuaNava) [inline pointmatcher/DataPointsFilters/MaxPointCount.cpp:83]: Can it happen that you swap a point that has already been swapped?

File: pointmatcher/DataPointsFilters/MaxPointCount.cpp (hunk 4 above)
Comment (aguenette) [reply pointmatcher/DataPointsFilters/MaxPointCount.cpp:74]: In the [documentation](https://en.cppreference.com/w/cpp/numeric/random), it says that the `default_random_engine` is implementation-defined and on my computer (`gcc` 7.5.0) it says that it's `std::minstd_rand0`.

I did some benchmark to evaluate the different ways random numbers can be generated:

int_vs_real_minstd_rand0

int_vs_real_minstd_rand

real_minimal_standard_vs_mersenne_twister_double

real_minimal_standard_vs_mersenne_twister_float

From that, we can clearly see that only modifying the old algorithm to use the C++11 `random` library is faster than using C `rand` function, and it also produce better results at shuffling `DataPoints`.

File: pointmatcher/DataPointsFilters/MaxPointCount.cpp (hunk 5 above)
Comment (aguenette) [reply pointmatcher/DataPointsFilters/MaxPointCount.cpp:83]: I think this is a possibility, but I don't know if it can be a problem. To avoid this, we would need keep track of the points that has been already swapped. Do you think it can be a problem?

**Comment by pomerlef** [comment]
Don't hesitate to open new issues if needed. I'll assume that this PR is ready for merge.
